### ISSUE TITLE
Issue starting the app

### ISSUE THREAD

**Issue by khalid-hussain** [Doublevil/Houhou-SRS#2]
Hi there,

I can't even start the app and am presented with the following error message:
````
---------------------------
Fatal error
---------------------------
It appears that Houhou has been vanquished by an evil XamlParseException.

Houhou will now shutdown. Sorry for the inconvenience.

Houhou's last words were: "Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception.". Oh the pain it must have been.



Please send me a mail report along with your log file if you think I should fix the issue.

Do you want to open the log?
---------------------------
Yes   No   Cancel   
---------------------------
````

And here is the log:
````
[2015-08-08 00:36:16,892] INFO - Loading sets...
[2015-08-08 00:36:16,892] INFO - Loading sets...
[2015-08-08 00:36:18,144] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-08 00:36:18,151] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-08 00:36:18,152] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-08 00:36:18,144] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-08 00:36:18,174] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-08 00:36:18,897] INFO - Finished loading sets.
[2015-08-08 00:36:26,103] INFO - Finished loading sets.
[2015-08-08 00:36:34,124] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-08 00:36:37,039] WARN - Received "OpenOrFocus" pipe command.
[2015-08-08 00:37:10,541] INFO - Loading sets...
[2015-08-08 00:37:10,541] INFO - Loading sets...
[2015-08-08 00:37:10,587] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-08 00:37:10,594] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-08 00:37:10,596] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-08 00:37:10,596] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-08 00:37:10,596] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-08 00:37:10,610] INFO - Finished loading sets.
[2015-08-08 00:37:11,357] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-08 00:37:11,976] INFO - Finished loading sets.
[2015-08-08 07:07:07,739] INFO - Loading sets...
[2015-08-08 07:07:07,739] INFO - Loading sets...
[2015-08-08 07:07:08,429] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-08 07:07:08,429] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-08 07:07:08,438] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-08 07:07:08,438] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-08 07:07:08,441] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-08 07:07:09,376] INFO - Finished loading sets.
[2015-08-08 07:07:14,451] INFO - Finished loading sets.
[2015-08-08 07:07:22,119] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-08 07:34:30,250] INFO - Loading sets...
[2015-08-08 07:34:30,250] INFO - Loading sets...
[2015-08-08 07:34:30,905] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-08 07:34:30,905] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-08 07:34:30,920] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-08 07:34:30,920] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-08 07:34:30,920] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-08 07:34:31,747] INFO - Finished loading sets.
[2015-08-08 07:34:35,257] INFO - Finished loading sets.
[2015-08-08 07:34:39,438] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-08 21:39:47,170] INFO - Loading sets...
[2015-08-08 21:39:47,171] INFO - Loading sets...
[2015-08-08 21:39:48,172] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-08 21:39:48,172] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-08 21:39:48,185] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-08 21:39:48,187] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-08 21:39:48,185] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-08 21:39:49,618] INFO - Finished loading sets.
[2015-08-08 21:39:54,999] INFO - Finished loading sets.
[2015-08-08 21:40:01,140] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-08 23:58:42,309] INFO - Loading sets...
[2015-08-08 23:58:42,309] INFO - Loading sets...
[2015-08-08 23:58:42,624] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-08 23:58:42,624] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-08 23:58:42,632] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-08 23:58:42,635] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-08 23:58:42,636] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-08 23:58:43,270] INFO - Finished loading sets.
[2015-08-08 23:58:46,937] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-08 23:58:47,255] INFO - Finished loading sets.
[2015-08-09 00:00:35,671] INFO - Loading sets...
[2015-08-09 00:00:35,666] INFO - Loading sets...
[2015-08-09 00:00:35,727] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\Default'.
[2015-08-09 00:00:35,737] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\SrsLevels\WaniKani'.
[2015-08-09 00:00:35,762] INFO - Finished loading sets.
[2015-08-09 00:00:35,763] INFO - Found set 'Default' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Default'.
[2015-08-09 00:00:35,763] INFO - Found set 'Kangxi' at 'C:\Users\Khalid\Documents\Houhou\Radicals\Kangxi'.
[2015-08-09 00:00:35,764] INFO - Found set 'WaniKani' at 'C:\Users\Khalid\Documents\Houhou\Radicals\WaniKani'.
[2015-08-09 00:00:36,553] FATAL - A fatal exception occured:
System.Windows.Markup.XamlParseException: Set property 'Xceed.Wpf.Toolkit.DateTimeUpDown.FormatString' threw an exception. ---> System.ArgumentException: 'yyyy-MM-dd H:mm:ss' is not a valid value for property 'FormatString'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-09 00:00:37,305] INFO - Finished loading sets.
````

Any idea how to solve this?

Thanks for your time.

**Comment by Doublevil** [comment]
Hello,
This is due to a locale coding error with the date parser, which expects dates in some of the internal files to be in your language. I'll definitely fix that someday. In the meantime, you can probably get it to work by setting the locale of the application to English with tools like the Microsoft AppLocale Utility.
Another workaround that has been confirmed by another user would be to set your calendar format to English.
Sorry for the inconvenience.

**Comment by khalid-hussain** [comment]
Hi,

I've tried MS AppLocale Utility using both English and Japanese language choices but it is still giving me the same error.

I'm using Windows 7 Home Premium 64-bit. My non-unicode language variable has been set to Arabic and my calendar is in Hijri. Is there some tutorial regarding using the AppLocale utility?

**Comment by Doublevil** [comment]
Maybe the AppLocale Utility won't work for this issue after all. I can't even get it to work properly on my side so I can't really help with that.
Changing your regional settings (calendar) to English (USA) would make it work, but I understand that it's a pain.
I'm not able to provide more support on this issue at the moment, but I'll make sure it's fixed for the next update, though it isn't planned for anytime soon.

**Comment by khalid-hussain** [comment]
Okay, Thanks.

**Comment by Larsie13** [comment]
This issue exists with several non-Gregorian calendars and is caused by the fact that Houhou uses a specific date format to display dates. Specifically, any calendar that does not support the **yyyy-MM-dd H:mm:ss** format would be affected.
Or I should say _existed_, because it is fixed in the master branch now and should thus be fixed in the next release, too.
